apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-setup
  name: kafka-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-setup
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: kafka-setup
    spec:
      containers:
      - args:
        - bash
        - -c
        - echo Waiting for Kafka to be ready... && cub kafka-ready -b kafka:29092
          1 20 && kafka-topics --create --if-not-exists --zookeeper zookeeper:2181
          --partitions 1 --replication-factor 1 --topic transactions
        env:
        - name: KAFKA_BROKER_ID
          value: ignored
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: ignored
        image: confluentinc/cp-kafka:5.1.4
        imagePullPolicy: ""
        name: kafka-setup
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
