version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example