version: '3.7'

services:

  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.1.4'
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: 
      - kafka-net

  kafka:
    image: 'confluentinc/cp-kafka:5.1.4'
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
    networks: 
      - kafka-net
    # command: "sleep 20s && \
    #           kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 3 --topic transactions'"      

networks:
  kafka-net:
    name: kafka-net
    driver: bridge